jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    steps:
    - name: Install Node
      uses: actions/setup-node@v2.3.0
      with:
        node-version: 18.9.0
    - name: Configure Git
      run: git config --global core.autocrlf input
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Install dependencies
      run: npm install --no-save
    # TODO: Remove once https://github.com/npm/cmd-shim/pull/64 has been merged
    - if: startsWith(matrix.os, 'windows')
      run: mv node.js not-node.js
    - name: Lint
      run: npm run lint
    strategy:
      matrix:
        os:
        - macos-12
        - ubuntu-22.04
        - windows-2022
name: Build
on:
- pull_request
- push
- workflow_dispatch
